"""A target key the server insists on choosing itself.

A column defined `GENERATED ALWAYS AS IDENTITY` refuses a value the client
chose. A repair has no choice but to choose one - the row it is fixing
already has a key - so before this, `migkit apply` could not repair a single
row on such a target:

    insert into "public"."ident" ("id", "v") values (7, 'a')
      on conflict ("id") do update set "v" = excluded."v";
    ERROR:  cannot insert a non-DEFAULT value into column "id"
    DETAIL:  Column "id" is an identity column defined as GENERATED ALWAYS.

That was measured by calling migkit's own `_apply_upsert`, not by reading
the SQL it builds - and with an ordinary table beside it as a control, so
the failure was the identity column rather than the path being broken.

It matters because `serial` behaves like `GENERATED BY DEFAULT` and accepts
an explicit value, so a schema "modernised" from serial to identity during
the migration stops accepting the very rows being migrated.

**`move` was never affected**, which is what keeps the fix narrow: `COPY`
into a generated-always column was measured to succeed with no clause at
all. Only the row-by-row repair had to change.
"""
import subprocess

import pytest

from migkit.config import Endpoint, Hop
from tests.conftest import needs_docker, psql

pytestmark = needs_docker

SHAPES = """
drop table if exists public.ident;
drop table if exists public.bydef;
drop table if exists public.plain;
create table public.ident (id int generated always as identity primary key,
                           v text);
create table public.bydef (id int generated by default as identity primary
                           key, v text);
create table public.plain (id int primary key, v text);
"""


def _engine(pg_pair, tmp_path):
    from migkit.engines.postgres import PostgresEngine
    hop = Hop(name="ident", engine="postgres",
              source=Endpoint(host="127.0.0.1", port=pg_pair["src"],
                              user="postgres", password="test"),
              target=Endpoint(host="127.0.0.1", port=pg_pair["dst"],
                              user="postgres", password="test"),
              databases=["postgres"], workers=2)
    hop.report_dir = lambda db=None: tmp_path
    return PostgresEngine(hop)


@pytest.fixture
def shapes(pg_pair):
    got = psql(pg_pair["dst"], SHAPES)
    assert got.returncode == 0, got.stderr
    return pg_pair


def _row(pg_pair, table, key):
    return psql(pg_pair["dst"],
                f"select v from public.{table} where id = {key}").stdout.strip()


def test_a_repair_lands_on_a_generated_always_key(shapes, tmp_path):
    """The failure this exists for, through the same call that could not do
    it before."""
    eng = _engine(shapes, tmp_path)
    eng._apply_upsert("dst", "postgres", "public.ident", {"id": 7},
                      {"v": "repaired"})
    assert _row(shapes, "ident", 7) == "repaired"

    # and it updates an existing row rather than only inserting
    eng._apply_upsert("dst", "postgres", "public.ident", {"id": 7},
                      {"v": "repaired twice"})
    assert _row(shapes, "ident", 7) == "repaired twice"


def test_the_ordinary_tables_are_unchanged(shapes, tmp_path):
    """The control. A fix that only works by making every insert special
    would be a different bug wearing the same clothes."""
    eng = _engine(shapes, tmp_path)
    for table in ("plain", "bydef"):
        eng._apply_upsert("dst", "postgres", f"public.{table}", {"id": 5},
                          {"v": "ok"})
        assert _row(shapes, table, 5) == "ok", table


def test_the_clause_is_emitted_only_where_it_is_needed(shapes, tmp_path):
    """`by default` is what `serial` behaves like and takes the value as
    given, so it must not be lumped in with `always`."""
    eng = _engine(shapes, tmp_path)
    always = eng._insert_override("dst", "postgres", "public.ident",
                                  ["id", "v"])
    assert always == " overriding system value", repr(always)
    for table in ("public.bydef", "public.plain"):
        assert eng._insert_override("dst", "postgres", table,
                                    ["id", "v"]) == "", table
    # a write that does not touch the identity column needs no clause
    assert eng._insert_override("dst", "postgres", "public.ident",
                                ["v"]) == ""


def test_the_lookup_is_cached_and_survives_being_asked_twice(shapes,
                                                              tmp_path):
    """This used to assert the name of the private cache dict, and broke
    the moment that dict was renamed - while the behaviour it cared about
    was fine. It now asks the question an operator would: does the second
    call answer the same as the first, without a second round trip."""
    eng = _engine(shapes, tmp_path)
    first = eng._insert_override("dst", "postgres", "public.ident", ["id"])
    assert first == " overriding system value", repr(first)

    calls = []
    real = eng._psql
    eng._psql = lambda *a, **k: (calls.append(a), real(*a, **k))[1]
    again = eng._insert_override("dst", "postgres", "public.ident", ["id"])
    assert again == first, (again, first)
    assert calls == [], calls   # answered from the cache, no query


def test_a_bulk_copy_needs_no_clause_at_all(shapes):
    """Why the fix is confined to the repair path: the mover uses COPY, and
    COPY is not subject to the restriction. Measured rather than assumed,
    because the opposite belief would have produced a much wider change."""
    # COPY FROM STDIN needs real stdin, which `psql -c` does not provide
    got = subprocess.run(
        ["docker", "exec", "-i", "-e", "PGPASSWORD=test",
         "migkit-test-pg-dst", "psql", "-U", "postgres", "-c",
         "copy public.ident (id, v) from stdin"],
        input="11\tfrom-copy\n", capture_output=True, text=True)
    assert got.returncode == 0, got.stderr
    assert "COPY 1" in got.stdout, got.stdout
    assert _row(shapes, "ident", 11) == "from-copy"


def test_the_server_still_refuses_without_the_clause(shapes):
    """The restriction is real and still there - this fix works around it,
    it does not remove it, and a test that stopped failing here would mean
    the sandbox had changed rather than that the bug was gone."""
    refused = psql(shapes["dst"],
                   "insert into public.ident (id, v) values (99, 'x')")
    assert refused.returncode != 0
    assert "non-DEFAULT value" in refused.stderr, refused.stderr
    allowed = psql(shapes["dst"], "insert into public.ident (id, v)"
                                  " overriding system value"
                                  " values (99, 'x')")
    assert allowed.returncode == 0, allowed.stderr


def test_engines_without_the_concept_say_nothing(tmp_path):
    """The base returns no clause, so an engine that has never heard of
    identity columns does not acquire PostgreSQL's syntax by inheritance."""
    from migkit.engines.base import Engine
    from migkit.engines.mysql import MySQLEngine
    hop = Hop(name="i", engine="postgres",
              source=Endpoint(host="127.0.0.1", port=1, user="u",
                              password="p"),
              target=Endpoint(host="127.0.0.1", port=1, user="u",
                              password="p"), databases=["x"])
    hop.report_dir = lambda db=None: tmp_path
    assert Engine(hop)._insert_override("dst", "x", "t", ["id"]) == ""
    assert MySQLEngine(hop)._insert_override("dst", "x", "t", ["id"]) == ""
