"""The troubleshooting guide, read off the code (backlog 42).

Every refusal migkit can stop with, found where it is raised, so the guide
cannot fall behind the code: `python -m migkit.troubleshooting` writes
`docs/troubleshooting.md`, and a test fails when the two differ. Each
refusal already says what to do in its own words; the guide adds where it
comes from, so the text an operator saw can be searched for.

A part of a message filled in at run time is shown as `<...>`. A refusal
whose words are built elsewhere (`capabilities.unavailable`, for one) is
listed under the function that builds them.
"""
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TITLE = "# Troubleshooting: every refusal, where it comes from"


def _text(node):
    """The message as a template, or None where it is not written here."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        out = []
        for part in node.values:
            if isinstance(part, ast.Constant):
                out.append(str(part.value))
            else:
                out.append("<...>")
        return "".join(out)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left, right = _text(node.left), _text(node.right)
        if left is None and right is None:
            return None
        return (left if left is not None else "<...>") + \
            (right if right is not None else "<...>")
    if isinstance(node, ast.IfExp):
        a, b = _text(node.body), _text(node.orelse)
        if a is None and b is None:
            return None
        return (a or "<...>") if a == b else \
            f"{a or '<...>'} | {b or '<...>'}"
    return None


def refusals():
    """[(module, function, template)] for every `raise SystemExit(...)`
    whose words are written where it is raised, in file order."""
    out = []
    for path in sorted(ROOT.rglob("*.py")):
        tree = ast.parse(path.read_text())
        module = str(path.relative_to(ROOT.parent))
        for fn in ast.walk(tree):
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for node in ast.walk(fn):
                if not (isinstance(node, ast.Raise)
                        and isinstance(node.exc, ast.Call)
                        and getattr(node.exc.func, "id", "") == "SystemExit"
                        and node.exc.args):
                    continue
                text = _text(node.exc.args[0])
                if text is None or not text.strip("<.> "):
                    continue
                out.append((module, fn.name, " ".join(text.split())))
    seen, unique = set(), []
    for item in out:
        if item not in seen:
            seen.add(item)
            unique.append(item)
    return unique


def render():
    lines = [TITLE, "",
             "Generated by `python -m migkit.troubleshooting` from the"
             " code; do not edit.",
             "Each entry is the message as migkit prints it, with the parts"
             " filled in at run time shown as `<...>`, under the part of"
             " migkit that raises it. The message says what to do.", ""]
    current, seen = None, set()
    for module, fn, text in refusals():
        if (module, text) in seen:
            continue
        seen.add((module, text))
        if module != current:
            lines += [f"## `{module}`", ""]
            current = module
        # the function's name is not given: some are named for the
        # program they drive, and a program's name is not for the reader
        lines += [f"* {text}", ""]
    return "\n".join(lines).rstrip() + "\n"


def main():
    target = ROOT.parent / "docs" / "troubleshooting.md"
    target.write_text(render())
    print(f"{target}: {len(refusals())} refusals")


if __name__ == "__main__":
    main()
